import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


import React, {useRef} from 'react'
import * as tf from '@tensorflow/tfjs'
import * as facemesh from '@tensorflow-models/facemesh'
import Webcam from 'react-webcam'

export default function Home() {

    const webcamRef = useRef(null)
    const canvasRef = useRef(null)

    const useFacemesh = async () => {

    }

  return (
    <div className={styles.container}>
      <Head>
        <title>xktensormesh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        {/* <header className='app-header'> */}

        <Webcam ref={webcamRef} style={
          {
            position: 'absolute',
            marginLeft: 'auto',
            marginRight: 'auto',
            left: 0,
            right: 0,
            textAlign: 'center',
            zIndex:9,
            width: 640,
            height: 480,
          }
        }/>
        <canvas ref={canvasRef} style={
          {
            position: 'absolute',
            marginLeft: 'auto',
            marginRight: 'auto',
            left: 0,
            right: 0,
            textAlign: 'center',
            zIndex:9,
            width: 640,
            height: 480,
          }
        }/>
        {/* </header> */}
      </main>
    </div>
  )
}
